---
- name: Create report bucket
  amazon.aws.s3_bucket:
    name: "{{ reports_aws_bucket_name }}"
    region: "{{ reports_aws_region }}"
    state: present
    acl: "{{ reports_aws_bucket_permissions }}"
    public_access: "{{ reports_aws_public_access }}"
    object_ownership: BucketOwnerPreferred

- name: Configure bucket for website
  community.aws.s3_website:
    name: "{{ reports_aws_bucket_name }}"
    state: present
    suffix: index.html
    error_key: index.html

- name: Put website files
  community.aws.s3_sync:
    bucket: "{{ reports_aws_bucket_name }}"
    file_root: "{{ role_path }}/files"
    permission: "{{ reports_aws_bucket_permissions }}"
    mime_map:
      .css: text/css
      .js: application/javascript
      .png: image/png
      .jpg: image/jpeg
      .jpeg: image/jpeg
      .gif: image/gif
      .svg: image/svg+xml

- name: Retrieve instance information
  amazon.aws.ec2_instance_info:
    filters: "{{ reports_aws_instance_filters }}"
    region: "{{ reports_aws_region }}"
  register: ec2_instance_info

- name: Ensure build directory exists
  ansible.builtin.file:
    path: "{{ playbook_dir }}/.build"
    state: directory
  delegate_to: localhost
  run_once: true

- name: Render tags-report locally
  ansible.builtin.template:
    src: tags_report.j2
    dest: "{{ playbook_dir }}/.build/tag-report.html"
  delegate_to: localhost
  run_once: true

- name: Put tags-report
  amazon.aws.s3_object:
    bucket: "{{ reports_aws_bucket_name }}"
    object: tag-report.html
    src: "{{ playbook_dir }}/.build/tag-report.html"
    mode: put
    permission: "{{ reports_aws_bucket_permissions }}"
    headers:
      ContentType: "text/html; charset=utf-8"
      ContentDisposition: inline
      CacheControl: "no-cache, no-store, must-revalidate"

- name: Get bucket objects
  amazon.aws.s3_object_info:
    bucket_name: "{{ reports_aws_bucket_name }}"
  register: bucket_objects

- name: Render index locally
  ansible.builtin.template:
    src: landing_page.j2
    dest: "{{ playbook_dir }}/.build/index.html"
  delegate_to: localhost
  run_once: true

- name: Put index.html
  amazon.aws.s3_object:
    bucket: "{{ reports_aws_bucket_name }}"
    object: index.html
    src: "{{ playbook_dir }}/.build/index.html"
    mode: put
    permission: "{{ reports_aws_bucket_permissions }}"
    headers:
      ContentType: "text/html; charset=utf-8"
      ContentDisposition: inline

- name: Print bucket url
  ansible.builtin.debug:
    msg: "Bucket URL: http://{{ reports_aws_bucket_name }}.s3-website.{{ reports_aws_region }}.amazonaws.com"