# code: language=ansible
---
- name: Play to Create Internet Gateway and attache to VPC
  hosts: localhost
  connection: local
  tasks:
    # Create Internet Gateway and attach it to VPC.  This allows instances on this VPC to reach the Internet
    - name: create vpc internet gateway for aws-demo1-vpc
      amazon.aws.ec2_vpc_igw:
        vpc_id: "{{ vpcid }}"
        region: "{{ ec2_region }}"
        tags:
          Name: aws_demo1_igw
          Demo: "AWS demo1"
      register: igw
#
    # This task adds a route to the internet from the subnet through the IGW
    - name: This creates a default route (0.0.0.0/0) for the subnet to
      amazon.aws.ec2_vpc_route_table:
        region: "{{ ec2_region }}"
        vpc_id: "{{ vpcid }}"
        subnets:
          - "{{ vpcsubnetid }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ igw.gateway_id }}"
        tags:
          Name: aws_demo1_default_route
          Demo: "AWS demo1"
